### ISSUE TITLE
近期Actions中的报错

### ISSUE THREAD

**Issue by Khan2001** [jscslld/hhu_health_report#7]
![Quicker_20220805_210320](https://user-images.githubusercontent.com/62993825/183084696-eafb3599-f80c-4fa2-9df2-0a311100b7c7.png)

上面是近几天我fork的仓库里workflow运行的报错，以前都是正常运行的，最近每次都是这个报错，但是打卡倒是打上了。

我在你的项目基础上只修改了 `report.yml` 中的

```
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
```

我检查了其他几个fork仓库的Actions，存在没有修改也有同样的报错的情况，不知道是什么原因呢？
